/*
 * generated by Xtext
 */
package fr.istic.idm.project.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.istic.idm.project.ui.internal.UIDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UIDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UIDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UIDslActivator.getInstance().getInjector(UIDslActivator.FR_ISTIC_IDM_PROJECT_UIDSL);
	}
	
}
