/*
* generated by Xtext
*/
package fr.istic.idm.project.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.istic.idm.project.services.PollDslGrammarAccess;

public class PollDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PollDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.istic.idm.project.parser.antlr.internal.InternalPollDslParser createParser(XtextTokenStream stream) {
		return new fr.istic.idm.project.parser.antlr.internal.InternalPollDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PollSystem";
	}
	
	public PollDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PollDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
