/*
* generated by Xtext
*/
package fr.istic.idm.project;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UIDslStandaloneSetup extends UIDslStandaloneSetupGenerated{

	public static void doSetup() {
		new UIDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

