/*
 * generated by Xtext
 */
package fr.istic.idm.project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PollDslUiModule extends fr.istic.idm.project.ui.AbstractPollDslUiModule {
	public PollDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
