/*
 * generated by Xtext
 */
package fr.istic.idm.project.ui.contentassist

import fr.istic.idm.project.ui.contentassist.AbstractPollDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PollDslProposalProvider extends AbstractPollDslProposalProvider {
}
