/*
 * generated by Xtext
 */
package fr.istic.idm.project.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.istic.idm.project.ui.internal.PollDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PollDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PollDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PollDslActivator.getInstance().getInjector(PollDslActivator.FR_ISTIC_IDM_PROJECT_POLLDSL);
	}
	
}
