/*
* generated by Xtext
*/
package fr.istic.idm.project;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PollDslStandaloneSetup extends PollDslStandaloneSetupGenerated{

	public static void doSetup() {
		new PollDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

