/*
 * generated by Xtext
 */
package fr.istic.idm.project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UIDslUiModule extends fr.istic.idm.project.ui.AbstractUIDslUiModule {
	public UIDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
