/**
 * generated by Xtext
 */
package fr.istic.idm.project.validation;

import fr.istic.idm.project.validation.AbstractPollDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PollDslValidator extends AbstractPollDslValidator {
}
