/**
 * generated by Xtext
 */
package fr.istic.idm.project.ui.contentassist;

import fr.istic.idm.project.ui.contentassist.AbstractUIDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class UIDslProposalProvider extends AbstractUIDslProposalProvider {
}
